version: '3'

services:
  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':1800'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.jUAn6EDxiGJ8YTcpMCtrfrzqeRC0mX4WMZabpNpj6hw'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.jUAn6EDxiGJ8YTcpMCtrfrzqeRC0mX4WMZabpNpj6hw'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    # Comment the following line to disable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "1800:1800"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config: ###< symfony/mercure-bundle ###
