version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:6000
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/usr/src/app   # Mount the current directory as a volume
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    ports:
      - 3002:3000
    depends_on:
      - prometheus
