# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          TYPE: '${{ secrets.TYPE }}'
          PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          PRIVATE_KEY_ID: '${{ secrets.PRIVATE_KEY_ID }}'
          PRIVATE_KEY: '${{ secrets.PRIVATE_KEY }}'
          CLIENT_EMAIL: '${{ secrets.CLIENT_EMAIL }}'
          CLIENT_ID: '${{ secrets.CLIENT_ID }}'
          AUTH_URI: '${{ secrets.AUTH_URI }}'
          TOKEN_URI: '${{ secrets.TOKEN_URI }}'
          AUTH_PROVIDER_X509_CERT_URL: '${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}'
          CLIENT_X509_CERT_URL: '${{ secrets.CLIENT_X509_CERT_URL }}'
